version: '3.3'
services:
  proxy:
    image: traefik:v2.2
    container_name: traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

  mongo:
    container_name: mongo
    image: mongo:3.4
    environment:
      - NODE_ENV
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - MONGO_DB
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - db:/data/db
    ports:
      - 27018:27017

  mongoui:
    container_name: mongoui
    image: mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.mongoui.rule=Host(`mongo.localhost`)'
      - 'traefik.http.routers.mongoui.entrypoints=web'

  api:
    container_name: api
    build:
      context: .
      dockerfile: dev.Dockerfile
    environment:
      - NODE_ENV
      - MONGO_COMMAND=mongodb://
      - MONGO_HOST
      - MONGO_DB
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - CORE_URL
      - API_KEY_PORTAL
      - JWT_SECRET
      - PORT
      - LDAP_URL
      - LDAP_USER
      - LDAP_PASSWORD
    volumes:
      - './:/src'
      - '/src/node_modules'
    restart: always
    depends_on:
      - mongo
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`api.localhost`)'
volumes:
  db:
    driver: local
