version: "3"
services:
  app:
    build:
      context: .
    environment:
      - NODE_ENV=test
      - PORT=8085
      - SERVER_HOST=localhost
      - USE_MOCK_DATA
      - MONGO_URI
    ports:
      - "8085:8085"
    command: npm run start
    volumes:
      - .:/usr/src/
      - /usr/node_modules
