# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Portal Backend - Master - Node.js CI

on:
  pull_request:
    types: [closed]
    branches:
      - 'master'

jobs:
  deploy_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          export_default_credentials: true
      - run: sudo apt-get install -qq -y gettext
      - run: echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY_PRODUCTION }}
      - run: gcloud --quiet config set run/region us-east1
      - run: gcloud --quiet config set project amicar-tech-255421
      - run: gcloud info
      - run: gcloud builds submit --tag gcr.io/amicar-tech-255421/portal-backend-production --async
      - run: sleep 120
      - run: gcloud run deploy portal-backend-production --image gcr.io/amicar-tech-255421/portal-backend-production --platform managed --set-env-vars NODE_ENV=production,MONGO_USERNAME=$MONGO_USERNAME,MONGO_PASSWORD=$MONGO_PASSWORD,MONGO_DB=amicar,MONGO_HOST=$MONGO_HOST,ROLLBAR_TOKEN=$ROLLBAR_TOKEN,JWT_SECRET=$JWT_SECRET,CORE_URL=$CORE_URL,API_KEY_PORTAL=$API_KEY_PORTAL
env:
  CI: true
  NODE_ENV: production
  MONGO_INITDB_DATABASE: admin
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: pass
  MONGO_DB: amicar
  MONGO_COMMAND: mongodb+srv://
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME_STAGING }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD_STAGING }}
  MONGO_HOST: ${{ secrets.MONGO_HOST_STAGING }}
  ROLLBAR_TOKEN: ${{ secrets.ROLLBAR_TOKEN_STAGING }}
  JWT_SECRET: ${{ secrets.JWT_SECRET_STAGING }}
  CORE_URL: ${{ secrets.CORE_URL_STAGING }}
  API_KEY_PORTAL: ${{ secrets.API_KEY_PORTAL_STAGING }}
  # TODO: change secrets
